export interface Artist {
  id: number,
  name: string,
  share: string,
  link: string,
  picture: string,
  picture_small: string,
  picture_medium: string,
  picture_big: string,
  picture_xl: string,
  nb_album: number,
  nb_fan: number,
  radio: boolean,
  tracklist: string,
  type: string,
}
